name: DamagePlugin
version: '1.0-SNAPSHOT'
main: io.github.Gabriel.damagePlugin.DamagePlugin
api-version: '1.21'
authors: [ Gabriel Nicolas ]
description: Plugin for No Man's Land for it's custom damage
commands:
  setDamage:
    description: set the damage for
    usage: /<command>